# Generated by Django 2.2 on 2019-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('father', models.CharField(max_length=30)),
                ('mother', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('gen', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to='profile_pics/')),
            ],
        ),
    ]
