# Generated by Django 2.2 on 2019-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='exit', max_length=30),
            preserve_default=False,
        ),
    ]
