# Generated by Django 2.2 on 2019-09-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='idno',
            new_name='num',
        ),
    ]
