# Generated by Django 2.2 on 2019-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30)),
                ('Answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
