# Generated by Django 2.2 on 2019-09-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chart1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contactno', models.IntegerField()),
            ],
        ),
    ]
