# Generated by Django 2.2 on 2019-09-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std',
            old_name='name',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='std',
            old_name='idno',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='std',
            name='contactno',
        ),
    ]
