# Generated by Django 2.2 on 2019-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190905_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sub',
            field=models.CharField(default='exit', max_length=30),
            preserve_default=False,
        ),
    ]
